const COPY: Record<string, string> = {
  'Welcome back': 'Titambire zvakare',
  'Sign in to your account': 'Pinda muakaundi yako',
  'Phone or Email': 'Nhamba yefoni kana email',
  'Password': 'Pasiwedhi',
  'Forgot password?': 'Wakanganwa pasiwedhi here?',
  'Login': 'Pinda',
  'or': 'kana',
  'Create Account': 'Gadzira Akaundi',
  'New to Tarisira?': 'Mutsva paTarisira here?',
  'Sign up free': 'Nyoresa mahara',
  'Back': 'Dzokera',
  'Continue': 'Enderera',
  'Enter your personal details': 'Nyora mashoko ako',
  'Full Name': 'Zita rizere',
  'Phone Number': 'Nhamba yefoni',
  "I agree to Tarisira's": 'Ndinobvumirana ne',
  'Terms of Service': 'Mitemo yekushandisa',
  'and': 'uye',
  'Privacy Policy': 'Gwaro rezvakavanzika',
  'Already have an account?': 'Une akaundi here?',
  'Your Business': 'Bhizinesi rako',
  'Tell us about your business': 'Tiudze nezvebhizinesi rako',
  'Business Name': 'Zita rebhizinesi',
  'Business Type': 'Rudzi rwebhizinesi',
  'Location': 'Nzvimbo',
  'Business Size': 'Kukura kwebhizinesi',
  'How many people work in your business?': 'Vanhu vangani vanoshanda mubhizinesi rako?',
  'Just me': 'Ini ndega',
  '2 – 5 people': 'Vanhu 2–5',
  '6 – 10 people': 'Vanhu 6–10',
  'More than 10': 'Vanhu vanopfuura gumi',
  'Currency': 'Mari inoshandiswa',
  'What currency does your business use?': 'Bhizinesi rako rinoshandisa mari ipi?',
  'You can select more than one': 'Unogona kusarudza inopfuura imwe',
  'Finish Setup': 'Pedzisa kuseta',
  "You're all set!": 'Zvese zvagadzirira!',
  'Your Tarisira free trial starts today.': 'Nguva yako yemahara yeTarisira inotanga nhasi.',
  'YOUR PLAN': 'CHIRONGWA CHAKO',
  '2 MONTHS FREE': 'MWEDZI MIVIRI MAHARA',
  'After your trial': 'Mushure menguva yako yekuedza',
  '$3 / month': '$3 pamwedzi',
  'Cancel anytime · No hidden fees': 'Kanzura chero nguva · Hapana mari yakavanzika',
  'Go to Dashboard': 'Enda kupeji guru',
  'Choose language': 'Sarudza mutauro',
  'Select your preferred language': 'Sarudza mutauro waunoda',
  'Continue in English': 'Enderera neChirungu',
  'Endarera muChiShona': 'Enderera muChiShona',
  'Language': 'Mutauro',
  'Choose your language. This affects both the app and the WhatsApp bot.': 'Sarudza mutauro wako. Izvi zvichachinja mutauro weapp neWhatsApp bot.',
  'Save': 'Chengeta',
  'Settings': 'Zvirongwa',
  'Business Profile': 'Nhoroondo yebhizinesi',
  'Notifications': 'Zviziviso',
  'Subscription': 'Kunyoresa',
  'Privacy & Security': 'Zvakavanzika nekuchengetedzwa',
  'Export Data': 'Tumira data kunze',
  'WhatsApp Bot': 'WhatsApp Bot',
  'Help & Support': 'Rubatsiro nerutsigiro',
  'Free Trial · 60 days left': 'Nguva yemahara · kwasara mazuva 60',
  'Log Out': 'Buda',
  'Log out?': 'Unoda kubuda here?',
  'You will need to sign in again.': 'Uchafanira kupinda zvakare.',
  'Cancel': 'Kanzura',
  'Coming soon': 'Zvichauya munguva pfupi',
  'This page is not built yet.': 'Peji rino harisati ragadzirwa.',
  'Home': 'Kumba',
  'Stock': 'Zvinhu zviri mudura',
  'Sales': 'Kutengesa',
  'Debtors': 'Vane zvikwereti',
  'Reports': 'Mishumo',
  'Good morning': 'Mangwanani akanaka',
  'Good afternoon': 'Masikati akanaka',
  'Good evening': 'Manheru akanaka',
  'Boss': 'Shefu',
  "Here's your business overview": 'Heino pfupiso yebhizinesi rako',
  "Today's Sales": 'Zvatengesa nhasi',
  'transactions': 'kutengeserana',
  'Debts Owed': 'Zvikwereti zvinofanira kubhadharwa',
  'debtors': 'vane zvikwereti',
  'Products': 'Zvigadzirwa',
  'Low Stock': 'Zvinhu zvava kupera',
  'Needs attention': 'Zvinoda kutarisirwa',
  'Sales This Week': 'Kutengesa kwesvondo rino',
  '+ Record Sale': '+ Nyora zvawatengesa',
  'WhatsApp': 'WhatsApp',
  'Reminders': 'Zviyeuchidzo',
  'Monthly Sales': 'Kutengesa kwemwedzi',
  'Stock Value': 'Kukosha kwezvinhu zviri mudura',
  'Total Debt': 'Chikwereti chose',
  'Sales Report': 'Mushumo wekutengesa',
  'Revenue, products & trends': 'Mari yapinda, zvigadzirwa nemafambiro',
  'Stock Report': 'Mushumo wedura rezvinhu',
  'Levels, value & movement': 'Huwandu, kukosha nekufamba kwezvinhu',
  'Debt Report': 'Mushumo wezvikwereti',
  'Outstanding & paid debts': 'Zvikwereti zvisati zvabhadharwa nezvabhadharwa',
  'Sales by Category': 'Kutengesa zvichienderana nerudzi',
  'Today': 'Nhasi',
  'Week': 'Svondo',
  'Month': 'Mwedzi',
  'Monthly Trend': 'Mafambiro emwedzi',
  'Recent Transactions': 'Kutengeserana kwazvino',
  'No sales recorded yet.': 'Hapana chatengeswa panguva ino.',
  "Tap '+ Record Sale' to start.": "Baya '+ Nyora zvawatengesa' kuti utange.",
  'Search products...': 'Tsvaga zvigadzirwa...',
  '+ Add': '+ Wedzera',
  'running low on stock': 'zvava kupera mudura',
  'In Stock': 'Zviripo mudura',
  'No products found.': 'Hapana zvigadzirwa zvawanikwa.',
  'Total Outstanding': 'Chikwereti chose chisati chabhadharwa',
  'Search debtors...': 'Tsvaga vane zvikwereti...',
  'Due Soon': 'Nguva yekubhadhara yava pedyo',
  'No debtors found. Tap a debtor to mark them as paid.': 'Hapana vane zvikwereti vawanikwa. Baya munhu kuti uratidze kuti abhadhara.',
  'Due today': 'Inofanira kubhadharwa nhasi',
  'Due tomorrow': 'Inofanira kubhadharwa mangwana',
  'No debtors': 'Hapana vane zvikwereti',
  'Create Reminder': 'Gadzira chiyeuchidzo',
  'Select Debtor': 'Sarudza ane chikwereti',
  'Message Preview': 'Tarisa meseji',
  'Send On': 'Tumira musi wa',
  'Tomorrow': 'Mangwana',
  'Custom': 'Sarudza rimwe zuva',
  'Will be sent via WhatsApp to': 'Ichatumirwa neWhatsApp kuna',
  'Schedule Reminder': 'Ronga chiyeuchidzo',
  'No reminders scheduled yet': 'Hapana zviyeuchidzo zvakarongwa',
  'Sending': 'Kutumira',
  'scheduled': 'zvakarongwa',
  'active debtors': 'vane zvikwereti vari kushanda',
  'Debtor Breakdown': 'Rondedzero yevane zvikwereti',
  'No outstanding debts. Nice work!': 'Hapana zvikwereti zvasara. Waita zvakanaka!',
  'Download PDF': 'Dhawunirodha PDF',
  'Export your complete business data at any time. Your information always belongs to you.': 'Unogona kutora data rose rebhizinesi rako chero nguva. Mashoko ako ndeako.',
  'Format': 'Mafomati',
  'Formatted report, ready to share': 'Mushumo wakarongwa, wagadzirira kugoverwa',
  'Raw data for spreadsheets': 'Data risina kurongwa remaspreadsheet',
  'Native Excel workbook (.xlsx)': 'Faira reExcel (.xlsx)',
  'Date Range': 'Nguva yemazuva',
  'This Month': 'Mwedzi uno',
  'Last Month': 'Mwedzi wapfuura',
  'All Time': 'Nguva yose',
  'Contact us': 'Taura nesu',
  'Chat on WhatsApp': 'Taura nesu paWhatsApp',
  'Email support': 'Tsigiro neemail',
  'Frequently asked questions': 'Mibvunzo inowanzo bvunzwa',
  'Save Changes': 'Chengeta zvachinja',
  'No connection': 'Hapana kubatana neinternet',
  'Please check your internet connection and try again.': 'Tarisa internet yako woedza zvakare.',
  'Retry': 'Edza zvakare',
  'Last cached data': 'Data rakapedzisira kuchengetwa',
  "Today's sales": 'Zvatengesa nhasi',
  'Transactions': 'Kutengeserana',
  'Top product': 'Chigadzirwa chakatengesa zvakanyanya',
  'Only': 'Chete',
  'Sell Price': 'Mutengo wekutengesa',
  'Cost Price': 'Mutengo wekutenga',
  '+ Add Stock': '+ Wedzera mudura',
  '− Remove': '− Bvisa',
  'Stock History': 'Nhoroondo yedura',
  'No stock movements yet.': 'Hapana shanduko yedura parizvino.',
  'Product': 'Chigadzirwa',
  'Quantity': 'Huwandu',
  'Unit Price': 'Mutengo wechinhu chimwe',
  'Total': 'Zvose',
  'Customer (optional)': 'Mutengi (haafaniri kuzadza)',
  'Payment Method': 'Nzira yekubhadhara',
  'Cash': 'Mari yepamaoko',
  'Mobile Money': 'Mari yefoni',
  'Card': 'Kadhi',
  'Credit': 'Chikwereti',
  'Save Sale': 'Chengeta zvawatengesa',
  'Sale saved': 'Zvawatengesa zvachengetwa',
  'Check the quantity': 'Tarisa huwandu',
  'Enter at least 1.': 'Isa nhamba isingasviki imwe chete.',
  'Not enough stock': 'Zvinhu zviri mudura hazvina kukwana',
  'Enter an amount': 'Isa mari',
  'Enter how much was paid.': 'Isa mari yakabhadharwa.',
  'This debtor has been fully paid or no longer exists.': 'Chikwereti ichi chabhadharwa chose kana kuti munhu uyu haachipo.',
  'Outstanding Balance': 'Chikwereti chisati chabhadharwa',
  'Record a payment ($)': 'Nyora mubhadharo ($)',
  'Record Payment': 'Nyora mubhadharo',
  'Send Reminder': 'Tumira chiyeuchidzo',
  'Payment History': 'Nhoroondo yemabhadharo',
  'Current Balance': 'Chikwereti chiripo',
  'Too many to remove': 'Zvakawandisa kubvisa',
  'units': 'zvinhu',
  'Add Product': 'Wedzera chigadzirwa',
  'Product name': 'Zita rechigadzirwa',
  'Category': 'Rudzi',
  'Price per unit ($)': 'Mutengo wechinhu chimwe ($)',
  'Quantity in stock': 'Huwandu huri mudura',
  'Save Product': 'Chengeta chigadzirwa',
  'Add Debtor': 'Wedzera ane chikwereti',
  'Customer name': 'Zita remutengi',
  'Amount owed ($)': 'Mari inokweretwa ($)',
  'Due in (days)': 'Nguva yasara (mazuva)',
  'Save Debtor': 'Chengeta ane chikwereti',
  'Missing details': 'Mashoko haana kukwana',
  'Enter a name, a price and a quantity.': 'Isa zita, mutengo nehuwandu.',
  'Enter a name and the amount owed.': 'Isa zita nemari inokweretwa.',
  'Sales Alerts': 'Zviziviso zvekutengesa',
  'When a sale is recorded': 'Kana kutengesa kwanyorwa',
  'Low Stock Alerts': 'Zviziviso zvezvinhu zvava kupera',
  'When stock runs low': 'Kana zvinhu zvava kupera mudura',
  'Payment Reminders': 'Zviyeuchidzo zvemabhadharo',
  'Debt payment reminders': 'Zviyeuchidzo zvekubhadhara chikwereti',
  'Daily Summary': 'Pfupiso yezuva',
  'Daily business digest': 'Pfupiso yebhizinesi yezuva',
  'Weekly Report': 'Mushumo wesvondo',
  'Weekly performance stats': 'Huwandu hwekushanda kwesvondo',
  'Marketing Updates': 'Mashoko matsva ekushambadza',
  'Tips and product updates': 'Mazano nemashoko matsva ezvigadzirwa',
  'STANDARD PLAN': 'CHIRONGWA CHAKAJAIKA',
  'Cancel anytime · No contracts': 'Kanzura chero nguva · Hapana chibvumirano',
  'Bank Transfer': 'Kutumira mari kubhangi',
  'Local or international': 'Munyika kana kune dzimwe nyika',
  'Subscribe': 'Nyoresa',
  'Pay $3.00': 'Bhadhara $3.00',
  'Payments are not connected yet.': 'Nzira dzekubhadhara hadzisati dzabatanidzwa.',
  'CURRENT PLAN': 'CHIRONGWA CHAZVINO',
  'FREE TRIAL': 'NGUVA YEMAHARA YEKUEDZA',
  'days remaining': 'mazuva asara',
  'Trial ends': 'Nguva yekuedza inopera',
  'After your free trial': 'Mushure menguva yako yemahara yekuedza',
  'Subscribe Now': 'Nyoresa izvozvi',
  "What's included": 'Zviri muchirongwa',
  'Unlimited products & sales': 'Zvigadzirwa nekutengesa zvisina muganhu',
  'Debt management & reminders': 'Kutarisira zvikwereti nezviyeuchidzo',
  'Business reports': 'Mishumo yebhizinesi',
  'WhatsApp bot (English & Shona)': 'WhatsApp bot (Chirungu neChiShona)',
  'Data export (PDF & CSV)': 'Kutumira data (PDF neCSV)',
  'Priority support': 'Rubatsiro rwekutanga',
  'Total Revenue': 'Mari yose yapinda',
  'Daily Sales': 'Kutengesa kwezuva',
  'Top Products': 'Zvigadzirwa zvinotengesa zvakanyanya',
  'Export CSV': 'Tumira CSV kunze',
  'Total Products': 'Huwandu hwezvigadzirwa',
  'Low Stock Alert': 'Yambiro: zvinhu zvava kupera',
  'All Products': 'Zvigadzirwa zvose',
  'Download Report': 'Dhawunirodha mushumo',
  'Download CSV': 'Dhawunirodha CSV',
  'Download Excel-compatible (.xls)': 'Dhawunirodha faira reExcel (.xls)',
  'Preparing PDF…': 'PDF iri kugadzirwa…',
  'Preparing CSV…': 'CSV iri kugadzirwa…',
  'Preparing Excel…': 'Faira reExcel riri kugadzirwa…',
  'Preparing export…': 'Mafaira ari kugadzirwa…',
  'Excel-compatible spreadsheet (.xls)': 'Faira rinoenderana neExcel (.xls)',
  'Export all reports as PDF': 'Dhawunirodha mishumo yose sePDF',
  'Export all reports as CSV': 'Dhawunirodha mishumo yose seCSV',
  'Export all reports as Excel': 'Dhawunirodha mishumo yose seExcel',
  'Export failed': 'Kutumira mafaira kwakundikana',
  'There are no records to export yet.': 'Hapana zvinyorwa zvekutumira parizvino.',
  'The report could not be exported.': 'Mushumo watadza kutumirwa.',
  'The reports could not be exported.': 'Mishumo yatadza kutumirwa.',
  'Sharing is unavailable on this device.': 'Kugovera mafaira hakusi kuwanikwa pamudziyo uyu.',
  'Allow pop-ups to print or save the PDF report.': 'Bvumira pop-up kuti uprinte kana kuchengetedza mushumo wePDF.',
  'Allow pop-ups to print or save the reports as PDF.': 'Bvumira pop-up kuti uprinte kana kuchengetedza mishumo sePDF.',
  'File storage is unavailable on this device.': 'Kuchengetera mafaira hakusi kuwanikwa pamudziyo uyu.',
  'Tuckshop': 'Chitoro chidiki',
  'Clothing store': 'Chitoro chembatya',
  'Salon': 'Saloni',
  'Restaurant': 'Resitorendi',
  'Hardware': 'Chitoro chezvokuvakisa',
  'Other': 'Zvimwe',
  'Zimbabwe Dollar': 'Dhora reZimbabwe',
  'South African Rand': 'Randi reSouth Africa',
  'Tanzanian Shilling': 'Shiringi reTanzania',
  'British Pound': 'Paundi reBritain',
  'Euro': 'Euro',
  'e.g. Rice 5kg': 'semuenzaniso: Mupunga 5kg',
  'e.g. Groceries': 'semuenzaniso: Zvekudya',
  'e.g. John': 'semuenzaniso: John',
  'Type a message': 'Nyora meseji',
  'Business Assistant · Online': 'Mubatsiri webhizinesi · Ari pamhepo',
  'Welcome back, Boss!': 'Titambire zvakare, shefu!',
  'What would you like to do?': 'Munoda kuita chii?',
  "Today's sales:": 'Zvatengesa nhasi:',
  'transactions recorded.': 'kutengeserana kwanyorwa.',
  'Best seller:': 'Chakatengesa zvakanyanya:',
  'Outstanding debtors:': 'Vane zvikwereti vasati vabhadhara:',
  'None': 'Hapana',
  'Total:': 'Zvose:',
  'Type PAY [name] [amount] to record payment.': 'Nyora BHADHARA [zita] [mari] kuti uchengete mubhadharo.',
  'You have': 'Une',
  'products.': 'zvigadzirwa.',
  'running low on stock.': 'zvava kupera mudura.',
  'This month:': 'Mwedzi uno:',
  'in sales,': 'zvatengeswa,',
  'outstanding.': 'zvisati zvabhadharwa.',
  "Sorry, I didn't catch that. Here's what I can help with:": 'Tine urombo, handina kunzwisisa. Izvi ndizvo zvandinogona kukubatsira nazvo:',
  'Tap to start': 'Baya kuti utange',
  'TARISIRA': 'TARISIRA',
};

const MONTHS: Record<string, string> = {
  January: 'Ndira', February: 'Kukadzi', March: 'Kurume', April: 'Kubvumbi', May: 'Chivabvu', June: 'Chikumi',
  July: 'Chikunguru', August: 'Nyamavhuvhu', September: 'Gunyana', October: 'Gumiguru', November: 'Mbudzi', December: 'Zvita',
  Jan: 'Ndira', Feb: 'Kukadzi', Mar: 'Kurume', Apr: 'Kubvumbi', Jun: 'Chikumi', Jul: 'Chikunguru', Aug: 'Nyamavhuvhu',
  Sep: 'Gunyana', Oct: 'Gumiguru', Nov: 'Mbudzi', Dec: 'Zvita',
};

export function shonaText(text: string): string {
  const direct = COPY[text];
  if (direct) return direct;

  let translated = text;
  translated = translated.replace(/^(\d+) transactions?$/, (_match, count: string) => `${count} kutengeserana`);
  translated = translated.replace(/^(\d+) debtors?$/, (_match, count: string) => `${count} vane zvikwereti`);
  translated = translated.replace(/^(\d+) active debtors?$/, (_match, count: string) => `${count} vane zvikwereti vari kushanda`);
  translated = translated.replace(/^(\d+) products? running low on stock$/, (_match, count: string) => `${count} zvigadzirwa zvava kupera mudura`);
  translated = translated.replace(/^Due in (\d+) days?$/, (_match, count: string) => `Inofanira kubhadharwa mumazuva ${count}`);
  translated = translated.replace(/^Sending (.+) · scheduled (.+)$/, (_match, when: string, date: string) => `Kutumira ${shonaText(when.toLowerCase())} · zvakarongwa ${date}`);
  translated = translated.replace(/^(.+) · (.+) \/ unit$/, (_match, category: string, price: string) => `${shonaText(category)} · ${price} pachinhu`);
  translated = translated.replace(/^(\d+) units?$/, (_match, count: string) => `${count} zvinhu`);
  translated = translated.replace(/^Reorder at (\d+) units$/, (_match, count: string) => `Odhazve kana kwasara ${count} zvinhu`);
  translated = translated.replace(/^Only (\d+) (.+) left\.$/, (_match, count: string, item: string) => `${count} chete zve${shonaText(item)} zvasara.`);
  translated = translated.replace(/^Export as (.+)$/, (_match, format: string) => `Tumira ${format} kunze`);
  translated = translated.replace(/^\$(\d+(?:\.\d+)?) \/ month$/, (_match, amount: string) => `$${amount} pamwedzi`);
  translated = translated.replace(/\b(January|February|March|April|May|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\b/g, (month) => MONTHS[month] ?? month);

  return COPY[translated] ?? translated;
}
